before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: xoi3le7C0gHajBGZr0kRKsvlZz7PtyeHBdFEQwNFpR45QqIwk9k8i7CahREAOMjKcUnk4v76PAYSSJEW38Qw0WygFnpQPHAZSvtvy5OCJcbmFw2CtcDIyDB6kIFssq4sfDlGI3IHtAnC2t57r6NMFJ+OcefXHBX5mICRFEEnzDj6lNemS4S3gaLj/CeGgzVqXQqS5ACsGioTaVuksVUszvQTNBjr5YzSMknajomFh2m3p1NAhHB5ACPdYqkLhY6e3NnsOn3W38Gd23UiEoybwZf4cKEXjwh5ggkF84TOpfcgInBQ/iOY49ZAj/eYYHGfnWjzT8yAoGJ6r3ohVWV53ZmwWH2uB7EkxiaT03xX9hfzbTjPOfYGGB5Lh4DDuu37HSqr1znVY4g3zJk1vCPyPo4qSqHPxVHMytMShQuCb0+D1N8VVgV3F2Y/dr50DBwtofkdcQ7XXqJS5LYDEJx3Fk7ZEJqqY8llZapEl96F/uVUxH5CHUTwz4vljwNjdrkWwiLnLE6R9oVIABzXVncM+kxetEUuaPlLroDnax1UVp7nVcQAttfUuOliHxHXBrF5QukHOpuwAeVOEoTEhUw57+Vf+U+J+ex5aINv/OXQ7RzQn1L0Z6VuWGcFqDtogIgCVzI4ILsjXpjj72jt/mttzCfYyXLDmhIu/ylMfpnmGQo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
